"""added

Revision ID: 6e42105abd0e
Revises: 9bb62450c5ec
Create Date: 2025-07-08 02:32:24.283501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e42105abd0e'
down_revision = '9bb62450c5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_out', sa.Time(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###
