"""add date

Revision ID: 9bb62450c5ec
Revises: d80c4e9d5a53
Create Date: 2025-02-05 03:13:49.958228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb62450c5ec'
down_revision = 'd80c4e9d5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
